### ISSUE TITLE
Setup motion sensing for Synology Surveillance motion events. 

### ISSUE THREAD

**Issue by stanvx** [stanvx/Home-Assistant-Configuration#20]
https://community.home-assistant.io/t/send-synology-surveillance-motion-events-to-ha-switch/59001/17

```
automation:
  - alias: 'Webhook endpoint to entry motion' ## http://hassio_ip:8123/api/webhook/motion_entrance ##
    hide_entity: true
    trigger:
      - platform: webhook
        webhook_id: motion_entrance
    action:
      - service: script.turn_on
        entity_id: script.trigger_ss_entrance_boolean
      - service: notify.hass_synochat
        data:
          message: "Entry motion webhook fired"
```
